[toolchain]

[features]
resolution = true
skip-lint = false

# [programs.localnet]
# solplay = "GqdmkZC5nqG8czabLKATHUJYVWkejqnZM2auAHUY6321"

[programs.devnet]
solplay = "GqdmkZC5nqG8czabLKATHUJYVWkejqnZM2auAHUY6321"

[registry]
url = "https://api.apr.dev"

# [provider]
# cluster = "Localnet"
# wallet = "~/.config/solana/id.json"

[provider]
cluster = "Devnet"
wallet = "admin.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
configure = "ts-node migrations/configure.ts"

[deploy]
timeout = 120
